
package discovery;

import android.app.ListFragment;
import android.content.Context;
import android.net.wifi.p2p.WifiP2pDevice;
import android.os.AsyncTask;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.ListView;
import android.widget.Spinner;
import android.widget.TextView;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.UUID;

/**
 * A simple ListFragment that shows the available services as published by the
 * peers
 */
public class WiFiDirectServicesList extends ListFragment {

    WiFiDevicesAdapter listAdapter = null;
    private WiFiServiceDiscoveryActivity mApp;
    private final static String TAG = "PTP_SList";

    interface DeviceClickListener {
        public void connectP2p(WiFiP2pService wifiP2pService);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
        mApp = (WiFiServiceDiscoveryActivity) getActivity();
        return inflater.inflate(R.layout.devices_list, container, false);
    }


    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        listAdapter = new WiFiDevicesAdapter(this.getActivity(),
                android.R.layout.simple_list_item_2, android.R.id.text1,
                new ArrayList<WiFiP2pService>());

        setListAdapter(listAdapter);

        Button b2 = (Button) this.getActivity().findViewById(R.id.button2);
        b2.setOnClickListener(
                new View.OnClickListener() {

                    @Override
                    public void onClick(View arg0) {

                        Date now = new Date();
                        String time = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss").format(now);

                        String myName = mApp.getMyDevice().deviceName;

                        String sub = myName.substring(myName.lastIndexOf('_') + 1);
                        MessageRow messageRow = new MessageRow(UUID.randomUUID(), myName , mApp.AUTOGENERATED, null, null,sub +"-at-"+ time);

                        String jsonMsg = mApp.shiftInsertMessage(messageRow);
                        WiFiServiceDiscoveryActivity.PTPLog.d(TAG, "Json autoGenerated: " + jsonMsg);
                        mApp.addMessage(messageRow); // for db

                    }
                });

        Button b3 = (Button) this.getActivity().findViewById(R.id.button3);
        b3.setOnClickListener(
                new View.OnClickListener() {

                    @Override
                    public void onClick(View arg0) {

                        WiFiChatFragment fragment = new WiFiChatFragment();
                        getFragmentManager().beginTransaction().replace(R.id.container_root,fragment).commit();
                        mApp.getStatusTxtView().setVisibility(View.GONE);
                    }
                });

        Button b4 = (Button) this.getActivity().findViewById(R.id.button4);
        b4.setOnClickListener(
                new View.OnClickListener() {

                    @Override
                    public void onClick(View arg0) {
                        mApp.createServerInfoFile();

                        new AsyncTask<Integer, Void, Void>() {
                            @Override
                            protected Void doInBackground(Integer... params) {
                                try {

                                    String sub = mApp.getMyDevice().deviceName.substring(mApp.getMyDevice().deviceName.lastIndexOf('_') + 1);

                                    SCPTest scpTest = new SCPTest();
                                    scpTest.SCPTestMain(sub);
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                                return null;
                            }

                        }.execute();

                    }
                });

        Spinner spinner = (Spinner) this.getActivity().findViewById(R.id.loop_spinner);
// Create an ArrayAdapter using the string array and a default spinner layout
        ArrayAdapter<CharSequence> adapter = ArrayAdapter.createFromResource(this.getActivity(),R.array.loop_array, android.R.layout.simple_spinner_item);
// Specify the layout to use when the list of choices appears
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
// Apply the adapter to the spinner
        spinner.setAdapter(adapter);

        spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> parentView, View selectedItemView, int position, long id) {
                String selected = parentView.getItemAtPosition(position).toString();
                //mApp.setLoopSec(Integer.parseInt(selected));
                mApp.setLoopSec(1000);

            }

            @Override
            public void onNothingSelected(AdapterView<?> parentView) {
                mApp.setLoopSec(1000);
            }

        });


    }


    @Override
    public void onListItemClick(ListView l, View v, int position, long id) {
        // TODO Auto-generated method stub
        ((DeviceClickListener) getActivity()).connectP2p((WiFiP2pService) l.getItemAtPosition(position));
        ((TextView) v.findViewById(android.R.id.text2)).setText("Connecting");

    }

    public class WiFiDevicesAdapter extends ArrayAdapter<WiFiP2pService> {

        private List<WiFiP2pService> items;

        public WiFiDevicesAdapter(Context context, int resource,
                int textViewResourceId, List<WiFiP2pService> items) {
            super(context, resource, textViewResourceId, items);
            this.items = items;
        }

        @Override
        public View getView(int position, View convertView, ViewGroup parent) {


            View v = convertView;

            if (v == null) {
                LayoutInflater vi = (LayoutInflater) getActivity()
                        .getSystemService(Context.LAYOUT_INFLATER_SERVICE);
                v = vi.inflate(android.R.layout.simple_list_item_2, null);
            }
            WiFiP2pService service = items.get(position);
            if (service != null) {
                TextView nameText = (TextView) v
                        .findViewById(android.R.id.text1);

                if (nameText != null) {
                    nameText.setText(service.device.deviceName + " - " + service.instanceName);
                }
                TextView statusText = (TextView) v
                        .findViewById(android.R.id.text2);
                statusText.setText(getDeviceStatus(service.device.status));
            }
            return v;
        }

        public List<WiFiP2pService> getItems() {
            return items;
        }
    }



    public static String getDeviceStatus(int statusCode) {
        switch (statusCode) {
            case WifiP2pDevice.CONNECTED:
                return "Connected";
            case WifiP2pDevice.INVITED:
                return "Invited";
            case WifiP2pDevice.FAILED:
                return "Failed";
            case WifiP2pDevice.AVAILABLE:
                return "Available";
            case WifiP2pDevice.UNAVAILABLE:
                return "Unavailable";
            default:
                return "Unknown";

        }
    }

}
